#pragma once

#include <charter/schema/key/rocksdb/activate_policy_set.hpp>
#include <charter/schema/key/rocksdb/active_policy_pointer.hpp>
#include <charter/schema/key/rocksdb/approval_rule.hpp>
#include <charter/schema/key/rocksdb/approval_state.hpp>
#include <charter/schema/key/rocksdb/approve_intent.hpp>
#include <charter/schema/key/rocksdb/attestation_record.hpp>
#include <charter/schema/key/rocksdb/attestation_status.hpp>
#include <charter/schema/key/rocksdb/cancel_intent.hpp>
#include <charter/schema/key/rocksdb/chain.hpp>
#include <charter/schema/key/rocksdb/claim_requirement.hpp>
#include <charter/schema/key/rocksdb/claim_type.hpp>
#include <charter/schema/key/rocksdb/create_policy_set.hpp>
#include <charter/schema/key/rocksdb/create_vault.hpp>
#include <charter/schema/key/rocksdb/create_workspace.hpp>
#include <charter/schema/key/rocksdb/destination_rule.hpp>
#include <charter/schema/key/rocksdb/destination_type.hpp>
#include <charter/schema/key/rocksdb/execute_intent.hpp>
#include <charter/schema/key/rocksdb/intent_action.hpp>
#include <charter/schema/key/rocksdb/intent_state.hpp>
#include <charter/schema/key/rocksdb/intent_status.hpp>
#include <charter/schema/key/rocksdb/limit_rule.hpp>
#include <charter/schema/key/rocksdb/operation_type.hpp>
#include <charter/schema/key/rocksdb/policy_rule.hpp>
#include <charter/schema/key/rocksdb/policy_set.hpp>
#include <charter/schema/key/rocksdb/primitives.hpp>
#include <charter/schema/key/rocksdb/propose_intent.hpp>
#include <charter/schema/key/rocksdb/revoke_attestation.hpp>
#include <charter/schema/key/rocksdb/role_id.hpp>
#include <charter/schema/key/rocksdb/time_lock_rule.hpp>
#include <charter/schema/key/rocksdb/transaction.hpp>
#include <charter/schema/key/rocksdb/transfer_parameters.hpp>
#include <charter/schema/key/rocksdb/upsert_attestation.hpp>
#include <charter/schema/key/rocksdb/upsert_destination.hpp>
#include <charter/schema/key/rocksdb/vault_model.hpp>
#include <charter/schema/key/rocksdb/vault_state.hpp>
#include <charter/schema/key/rocksdb/workspace_state.hpp>