#pragma once

#include <charter/schema/encoding/scale/activate_policy_set.hpp>
#include <charter/schema/encoding/scale/active_policy_pointer.hpp>
#include <charter/schema/encoding/scale/approval_rule.hpp>
#include <charter/schema/encoding/scale/approval_state.hpp>
#include <charter/schema/encoding/scale/approve_intent.hpp>
#include <charter/schema/encoding/scale/attestation_record.hpp>
#include <charter/schema/encoding/scale/cancel_intent.hpp>
#include <charter/schema/encoding/scale/claim_requirement.hpp>
#include <charter/schema/encoding/scale/create_policy_set.hpp>
#include <charter/schema/encoding/scale/create_vault.hpp>
#include <charter/schema/encoding/scale/create_workspace.hpp>
#include <charter/schema/encoding/scale/destination_rule.hpp>
#include <charter/schema/encoding/scale/destination_type.hpp>
#include <charter/schema/encoding/scale/execute_intent.hpp>
#include <charter/schema/encoding/scale/intent_state.hpp>
#include <charter/schema/encoding/scale/limit_rule.hpp>
#include <charter/schema/encoding/scale/policy_rule.hpp>
#include <charter/schema/encoding/scale/policy_set.hpp>
#include <charter/schema/encoding/scale/propose_intent.hpp>
#include <charter/schema/encoding/scale/revoke_attestation.hpp>
#include <charter/schema/encoding/scale/time_lock_rule.hpp>
#include <charter/schema/encoding/scale/transaction.hpp>
#include <charter/schema/encoding/scale/transfer_parameters.hpp>
#include <charter/schema/encoding/scale/upsert_attestation.hpp>
#include <charter/schema/encoding/scale/upsert_destination.hpp>