#pragma once

#include <charter/schema/transaction_error_code.hpp>
#include <scale/scale.hpp>

SCALE_DEFINE_ENUM_VALUE_LIST(
    charter::schema,
    transaction_error_code,
    charter::schema::transaction_error_code::invalid_transaction,
    charter::schema::transaction_error_code::unsupported_transaction_version,
    charter::schema::transaction_error_code::invalid_chain_id,
    charter::schema::transaction_error_code::invalid_nonce,
    charter::schema::transaction_error_code::invalid_signature_type,
    charter::schema::transaction_error_code::signature_verification_failed,
    charter::schema::transaction_error_code::workspace_exists,
    charter::schema::transaction_error_code::workspace_missing,
    charter::schema::transaction_error_code::vault_exists,
    charter::schema::transaction_error_code::policy_scope_missing,
    charter::schema::transaction_error_code::policy_set_exists,
    charter::schema::transaction_error_code::policy_set_missing,
    charter::schema::transaction_error_code::vault_scope_missing,
    charter::schema::transaction_error_code::active_policy_missing,
    charter::schema::transaction_error_code::workspace_missing_for_operation,
    charter::schema::transaction_error_code::intent_exists,
    charter::schema::transaction_error_code::policy_resolution_failed,
    charter::schema::transaction_error_code::intent_missing,
    charter::schema::transaction_error_code::intent_not_approvable,
    charter::schema::transaction_error_code::intent_expired,
    charter::schema::transaction_error_code::duplicate_approval,
    charter::schema::transaction_error_code::intent_already_executed,
    charter::schema::transaction_error_code::intent_not_executable,
    charter::schema::transaction_error_code::attestation_missing,
    charter::schema::transaction_error_code::limit_exceeded,
    charter::schema::transaction_error_code::destination_not_whitelisted,
    charter::schema::transaction_error_code::claim_requirement_unsatisfied,
    charter::schema::transaction_error_code::signer_quarantined,
    charter::schema::transaction_error_code::degraded_mode_active,
    charter::schema::transaction_error_code::authorization_denied,
    charter::schema::transaction_error_code::velocity_limit_exceeded,
    charter::schema::transaction_error_code::separation_of_duties_violated,
    charter::schema::transaction_error_code::destination_update_exists,
    charter::schema::transaction_error_code::destination_update_missing,
    charter::schema::transaction_error_code::destination_update_finalized,
    charter::schema::transaction_error_code::destination_update_not_executable,
    charter::schema::transaction_error_code::asset_missing,
    charter::schema::transaction_error_code::asset_disabled)
